### ISSUE TITLE
hang matlab under windows

### ISSUE THREAD

**Issue by xiangruili** [avivrosenberg/matlab-jsystem#2]
Thanks for the super fast jsystem solution. See my post at [Matlab Central for a comparison.](https://www.mathworks.com/matlabcentral/answers/338553-performance-of-system-dos-function) 

However with the same reg.exe query command, it hangs Matlab under Windows 7, Matlab 2017a.

cmd = 'reg.exe query HKEY_LOCAL_MACHINE\HARDWARE /s';
tic; [err, str] = jsystem(cmd); toc % this hangs matlab with or without 'noshell'

**Comment by avivrosenberg** [comment]
Hi, sorry for the delayed reply.

Don't know if it's still relevant but I'll try to help.

It's strange that a specific command causes it to hang while others work.
And unfortunately, I don't have a windows machine to test this on.
However, after staring at the code for a while I have a theory that it may be caused by excessive writing to `stderr`. Since in Matlab I can't run code asynchronously, I need to first read the subprocess' `stdout` and then its `stderr` sequentially. If the subprocess writes too much to `stderr` it may get stuck on IO because the parent process doesn't read from there and there may be an issue of buffers filling up.

To test my theory, you could:
1. Run the offending command from your shell, redirect `stdout` and `stderr` to different files and see whether indeed the command generates substantial content in `stderr`.
2. If that's the case, try changing the `false` to `true` in line 57 of the `jsystem.m` function, and run it again.

Hope this helps.
Aviv

**Comment by xiangruili** [comment]
Thanks for looking into the problem, Aviv.
I tried the following at Matlab Command Windows, but the errFile is empty:

    ! reg.exe query HKEY_LOCAL_MACHINE\HARDWARE /s 2>errFile

Please let me know if you need me to try something else.

**Comment by avivrosenberg** [comment]
Can you post the output of the command here? I.e. redirect `stdout` this time and post it.
I'll try to maybe reproduce with that.

BTW I edited my previous comment, there were some mistakes with the stream names.

**Comment by xiangruili** [comment]
In case it is related, I am running the test on Matlab 2017a under Windows 7 Professional.

The following from Matlab Command Window produced [stdOut.txt](https://github.com/avivrosenberg/matlab-jsystem/files/2009603/stdOut.txt), while stdErr.txt is empty:

    ! reg.exe query HKEY_LOCAL_MACHINE\HARDWARE /s 1>stdOut.txt 2>stdErr.txt

If I do the following, it gives the same output file as expected due to empty stderr:

    ! reg.exe query HKEY_LOCAL_MACHINE\HARDWARE /s >stdOut.txt 2>&1

Let me know if you need more information to diagnose. Thanks.

**Comment by avivrosenberg** [comment]
Hi @xiangruili. Thanks to your output example I was able to reproduce and fix this bug.
I have pushed commit a8c24f2d53ae46a5fe6409f661e570186d447ac5 with a fix.

Please test and let me know, thanks.

**Comment by xiangruili** [comment]
A quick test indicates the problem is fixed.  Following shows the result on my computer:

```
cmd = 'reg.exe query HKEY_LOCAL_MACHINE\HARDWARE /s';
tic; [err, str] = jsystem(cmd); toc
Elapsed time is 0.792617 seconds.

numel(str)
ans =
       95748

numel(regexp(str, '\r\n'))
ans = 
    369

numel(regexp(str, '\n'))
ans =
   369

tic; [err, str] = system(cmd); toc
Elapsed time is 3.527246 seconds.

numel(str)
ans =
       95382

numel(regexp(str, '\r\n'))
ans =
     0

numel(regexp(str, '\n'))
ans =
   372
```

The length difference is likely due to the '\r\n' vs '\n' in the output for Windows. Do you think it is a good idea to make the output more similar to that from `system`?

    if ispc, str = regexprep(str, '\r\n', '\n'); end % makes jsystem output almost the same as system

**Comment by avivrosenberg** [comment]
Thanks for confirming the fix. 👍 

I'm not sure where those differences come from since you ran everything on windows and I can't really test it on my machine.
Either way, I don't think it's a good idea to change the output without understanding why the line separators are different, because there may be more cases that we're not aware of...

**Comment by xiangruili** [comment]
The newline difference is OS specific: [https://en.wikipedia.org/wiki/Newline](https://en.wikipedia.org/wiki/Newline) .

Matlab system() makes the output with consistent for newline (\n), so it should be good for jsystem() to do the same.

Anyway this is not critical IMO. Thanks for the fix!

**Comment by avivrosenberg** [comment]
I know about OS-specific newline separators, what I meant is that it's not clear why you got those results since you ran both your tests on **windows** (one using `system` and the other with `jsystem`). I would expect the line separators to be the same. 

Since they weren't there are multiple possible explanations (in theory):
1. The command you ran returns output with `\r\n`. This means that `system` doesn't modify the output but something in `jsystem` does. If this is the case then it's better to find what that is and fix the problem there. 
I think this first case is the more likely one. If indeed that's the case then implementing your solution is not a good idea: Imagine if someone is running a program on windows that does return `\n` line separators (there are such cases) and s/he's using `system()` and relying on the output. Then when changing to `jsystem()` his output would change because of your fix and that may break something else depending on his output in a very subtle and hard to debug way...

2. The command you ran returns output with `\n`. This means that `system` does modify its output to match the OS. In this case, I would just update `jsystem` to do the same as `system` with a regex as you suggested. However, I don't think this case is likely at all. The docs for `system` mention nothing about any newline conversion.

3. It's something else I didn't think of. Since the regex doesn't cause the length to be **exactly** the same then this is also possible...


Again, we're probably in case 1, so this means I need to find out why `jsystem` behaves this way and fix it at the source instead of just applying a regex after the fact. I'll try to look into it sometime in the next few days...

Thanks

**Comment by xiangruili** [comment]
Thank you for looking into it. I meant this is not critical, but missed "not" :)
Here is more information which may be useful: 
1. The output of evalc('! cmd') and cmd > file under Windows all have \r\n line separator.
2. The output of system('cmd') in Octave under Windows also contains \r\n, different from Matlab.

So my guess is that it is case 2 you listed: Matlab system() makes output consistent across OS.

I think you can close the hanging issue, since it is fixed. The separator thing is another topic.

**Comment by avivrosenberg** [comment]
OK, this issue is closed, thanks. 👍 

Could you just please clarify what you said in your last message?
If you see only `\r\n` in all those cases, then why do you conclude it's matlab's `system()` that's modifying the output?
What I mean is that in order to check if we're in case 2 we need to write a small program or script that outputs `\n`, run it with `system()` on windows and see whether the result in matlab has `\r\n` while the original output (e.g. when running it directly) is `\n`.

**Comment by xiangruili** [comment]
That was just my guess. Different ways to capture the output (evalc, file redirestion and Octave system()) all show \r\n, while only matlab system() gives \n. 

If you need me to test anything, please just let me know. Thanks.
